### ISSUE TITLE
Erro ao executar comandos em versões do Elasticsearch superiores à 6.0

### ISSUE THREAD

**Issue by vinidf** [alefeans/elastic-stack#2]
Ao executar o seguinte comando no Elasticsearch 6.2.4

```
curl -XPUT http://localhost:9200/mycompany/funcionarios/1 -d '
{
  "nome": "João Silva",
  "idade": 19,
  "endereco": "Avenida da Magia",
  "hobbies": ["Tocar guitarra", "Acampar com a familia"],
  "interesses": "musica"
}'

```
O retorno é um erro com a seguinte mensagem: 

`{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}% `

**Comment by vinidf** [comment]
A partir da versão 6.0 do _Elasticsearch_, o cabeçalho _Content-Type_ é obrigatório: https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests

**Comment by alefeans** [comment]
Exatamente Vinicius ! Tem uma CLI bem legal feita por um dos engenheiros da Elastic que facilita bastante realizar as chamadas pro Elasticsearch:

https://discuss.elastic.co/t/why-elasticsearch-does-not-come-with-a-cli/99485/7

Ela já acrescenta o Header necessário e deixa as chamadas bem mais simples.

Vou adicionar uma observação no início do repositório. Muito obrigado !
